# Phonebooth Vision Configuration
# Copy this file to config.toml and modify as needed

[app]
data_dir = "data"
write_interval = 1.0
log_level = "DEBUG"

[app.camera]
id = 0
width = 1280
height = 720
fps = 30

[app.model]
name = "yolov8n.pt"
confidence = 0.25
iou = 0.5

[app.clothing]
enabled = true
model_type = "advanced"  # "simple", "advanced", or "fashionpedia"
model_name = "Salesforce/blip-image-captioning-base"  # Actual vision-language model
update_frequency = 1.0  # seconds between clothing updates
min_person_confidence = 0.5

[app.server]
enabled = true
server_type = "http"  # "http" or "file"
host = "0.0.0.0"
port = 8001
output_file = "clothing_detections.json"
